# Generated by Django 2.1.5 on 2019-02-11 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='posts',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
